#!/bin/sh

if [ "$2" == "standaloneWin32" ]; then
	rm -rf "${1/.exe/_Data}/uWebKit/Native/Windows"
	mkdir -p "${1/.exe/_Data}/uWebKit/Native/Windows"
	cp -R Assets/Editor/uWebKit/Native/Windows "${1/.exe/_Data}/uWebKit/Native/"	
else
	rm -rf "$1/uWebKit/Native/Mac/UWKProcess.app"
	mkdir -p "$1/Contents/uWebKit/Native/Mac"
	cp -R Assets/Editor/uWebKit/Native/Mac/UWKProcess.app "$1/Contents/uWebKit/Native/Mac"
fi


